name: syncable_example
description: Example demonstrating multi-node sync with syncable.
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  syncable:
    path: ..

dev_dependencies:
  test: ^1.24.0